# Shell variables
# Generated by 'wal'
wallpaper='/home/nikita/Pictures/wallpapers/wallpapersden.com_colorful-dots-space_3840x2160-art-scale-6_00x.jpg'

# Special
background='#080B12'
foreground='#97dbe2'
cursor='#97dbe2'

# Colors
color0='#080B12'
color1='#125463'
color2='#167689'
color3='#5D4D90'
color4='#A711A3'
color5='#1896A7'
color6='#21D5E1'
color7='#97dbe2'
color8='#69999e'
color9='#125463'
color10='#167689'
color11='#5D4D90'
color12='#A711A3'
color13='#1896A7'
color14='#21D5E1'
color15='#97dbe2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
